[book]
authors = ["Patrick Jackson"]
language = "en"
multilingual = false
src = "src"
title = "Galactic War Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true
git-repository-url = "https://github.com/arcuru/galactic-war"
edit-url-template = "https://github.com/arcuru/galactic-war/edit/main/docs/{path}"
